### ISSUE TITLE
in safeMintRange, do we really want to use uint16 to e.g. safe gas?

### ISSUE THREAD

**Issue by TimDaub** [whitecube-online/balot#29]
- Currently in `safeMintRange` we're using `uint16`. But that limits us to 2^16 iterations maximally
- Do we actually save gas by using `uint16` as Solidity's input packing is anyways not super obvious...
- Do we want to trade off functionality/correctness for saving gas here?

**Comment by lajarre** [comment]
I haven't yet found a clear explanation about input params packing in Solidity, so I tried some experiments:


  | Experiment | Gas Used
-- | -- | --
Minter deployment |   |  
  | 256-inputs | 491951
  | baseline | 501023
  | 32-inputs | 502295
  | loop-16 | 510089
  | canary | 790523
SafeMintRange |   |  
  | 256-inputs | 16437448
  | baseline | 16439393
  | 32-inputs | 16439437
  | loop-16 | 16452893
  | canary | 16453671
transferCollection |   |  
  | 256-inputs | 34415
  | 32-inputs | 34415
  | loop-16 | 34415
  | baseline | 34415
  | canary | 34437

- baseline: the actual code in https://github.com/whitecube-online/balot/pull/41
- 256-inputs: just move all inputs to `uint256`, which is the "worst case": no clever packing
- 32-inputs: move inputs to `uint32`
- loop-16: change the loop variable to `uint16`
- canary: add a lot dummy state in the Mint contract (should increase deployment significantly).

This has been tested using `gasUsed` on ethers transaction receipts, throughout the testScenarios.js file. This is thus using a Hardhat local chain.

Shall we reach the conclusion that there is no obvious optimization to do on inputs, and thus that we can move `start` and `end` to `uint256`?

**Comment by TimDaub** [comment]
> Shall we reach the conclusion that there is no obvious optimization to do on inputs, and thus that we can move `start` and `end` to `uint256`?

Yeah. But honestly, since none of the experiments showed any significant improvements, IMO we can move towards one of two things

- Understand what is the actual dollar cost if e.g. we minted today and if it's to high and we need to reduce it.

For now, given our time constraints, I'm more comfortable in just understanding what minting would cost right now on mainnet. So I'm closing.
