### ISSUE TITLE
Upon transferring ownership rights of the NFT collection to the minter, anyone could front run safeMintRange to take over ownership

### ISSUE THREAD

**Issue by TimDaub** [whitecube-online/balot#31]
- a fix can be to make Minter Ownable and safeMintRange onlyOwner
- for more details see #30

**Comment by lajarre** [comment]
It appears now to me there is no practical way we can move all of the `safeMintRange` logic in the constructor, as the only way for the Minter contract to call `Balot.safeMint` and make changes to the `Balot` storage would be that the `Minter` is itself the `Balot._owner` (I believe we could maybe do this if we know in advance the `Minter` address before deployment, which is I think possible but really unpractical and creating event more problems).

So, I'll go with Ownable.

**Comment by TimDaub** [comment]
> the only way for the Minter contract to call `Balot.safeMint` and make changes to the `Balot` storage would be that the `Minter` is itself the `Balot._owner` and makes direct calls (not delegate calls) to `safeMint`.

Yeah. I see the problem you're referencing. In order for the `Minter` to call `Balot.transferOwnership`, we'd somehow have to make sure that within `Minter.constructor': `msg.sender = Balot.owner()`. 

> I believe we could maybe do this if we know in advance the `Minter` address before deployment, which is I think possible but creates an even bigger security problem.

Not sure I'm following. From what I understand it'd depend on what equates `msg.sender` at the time of calling `Balot.transferOwnership` (in `Minter.constructor`) as it'd have to pass [`Ownable.onlyOwner`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b53c43242fc9c0e435b66178c3847c4a1b417cc1/contracts/access/Ownable.sol#L42). It's been a while since I've done these Solidity tutorials, but if I remember correctly then `msg.sender` can change depending on the transaction's internal call structure.

E.g. [here's a section on the Solidity docs](https://docs.soliditylang.org/en/develop/introduction-to-smart-contracts.html?highlight=DELEGATECALL#delegatecall-callcode-and-libraries) that talks about the benefits of `DELEGATECALL` with respect to `msg.sender`. But that stuff is kinda out of my comfort zone for now...

**Comment by lajarre** [comment]
> Not sure I'm following. From what I understand it'd depend on what equates `msg.sender` at the time of calling `Balot.transferOwnership` (in `Minter.constructor`) as it'd have to pass the `require` in [`Ownable.onlyOwner`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b53c43242fc9c0e435b66178c3847c4a1b417cc1/contracts/access/Ownable.sol#L42). It's been a while since I've done these Solidity tutorials, but if I remember correctly then `msg.sender` can change depending on the transaction's internal call structure.
> 
> E.g. [here's a section on the Solidity docs](https://docs.soliditylang.org/en/develop/introduction-to-smart-contracts.html?highlight=DELEGATECALL#delegatecall-callcode-and-libraries) that talks about the benefits of `DELEGATECALL` with respect to `msg.sender`. But that stuff is kinda out of my comfort zone for now...

AFAIK delegatecall is indeed the mechanism for allowing a contract (Minter) to call any other contract (Balot) with its own context (the context of Minter). This has two consequences: on the one hand, interestingly, it allows Balot's code to execute with Minter's `msg.sender`, the actual sender that is calling Minter (the Minter owner, "our wallet"). On the other hand, any result of such computations won't ever be written to Balot's storage, but only to Minter's storage.  
This looks to me like a fundamental limitation.
